FROM nvcr.io/nvidia/tritonserver:25.06-trtllm-python-py3
LABEL maintainer="kenny.zhou@insighttracking.cn"

RUN apt-get update && apt-get install -y cmake
RUN pip install pqi && pqi use ustc
RUN git clone https://gitclone.com/github.com/pytorch/audio.git && cd audio && git checkout c670ad8 && PATH=/usr/local/cuda/bin:$PATH python3 setup.py develop
COPY ./requirements.txt /workspace/requirements.txt
RUN pip install -r /workspace/requirements.txt
COPY run.sh /workspace/run.sh
WORKDIR /workspace